#!/bin/bash

# Bash script to execute each individual task

echo "Hello world from BashRUN!"

#user name
task_user=$1
echo "1 is $task_user"

#task name
task_name=$2
echo "2 is $task_name"

#task id
task_id=$3
echo "3 is $task_id"

#user email address
email=$4
echo "4 is $email"

#array of commands (comma separated)
num_of_commands=$5
echo "5: $num_of_commands"

commands=$6
echo "6: $commands"

#change the directory. move to the task directory
cd /var/www/html/worker/uploads/$task_id

#execute all the commands, one after the other.
for (( i=1; i<$num_of_commands; i++ ));do
	command=$(echo $commands| cut -d',' -f $i)
	$command
done



#compress the complete task directory
zip $task_id.zip *

#copy the results to the finished tasks directory
cp $task_id.zip ../../finished


#prepare the email to send it to user
TO_ADDRESS=$email
FROM_ADDRESS="work@worker.de"
SUBJECT="Worker: $task_name Task finished"
BODY="Hello $task_user! Your task $task with id: $folder is finished."

#send the email to user
#echo "${BODY}" | mail -s "${SUBJECT}" "${TO_ADDRESS}"  # -- -r "${FROM_ADDRESS}"


#search for the task in the file and chage status to FINISHED


filename="TasksList.csv"
while IFS='' read -r task || [[ -n "$task" ]]; do
	echo "hi"
	echo ${task//NEWs/FISNISHED} ; 
done < $filename > TasksList.csv.t ; mv TasksList.csv{.t,}

while IFS='' read -r task || [[ -n "$task" ]]; do
    echo "hi"
	echo ${task//NEWs/FISNISHED} ; 
done < $filename


#done
echo "done!"



