#!/bin/bash

# Bash script search for new tasks and run them

#awk -F "\"*,\"*" '{print $6}' TasksList.csv
# while read a ; do echo ${a//abc/XYZ}
#sed '0,/NEW/{s/NEW/YES/}' "$1"

unset n
while IFS='' read -r task || [[ -n "$task" ]]; do
	
	
	: $[n++]
	
	
	
	
	echo $n
	#echo "$task"
	
	
	task_status=$(echo $task| cut -d',' -f 6)
	#echo $task_status
	
	
	#If status is NEW, change the status and run the task.
	if [ $task_status == "NEW" ]; then
		#Change the status to RUNNING.
		
		#replace the word new with running		
		#sed -i "0,/\bNEW\b/d" "$1"
		#sed '0,/NEW/{/NEW/d;}' "$1"
		###sed -i '0,/NEW/{s/NEW/YES/}' "$1"
		
		sed -i '0,/\bNEW\b/{s/\bNEW\b/YES/}' "$1"
		
		
		#sed -i "$n d" "$1"
		#: $[n++]
		
		#echo ${task//NEW/RUNNNIGs} >> "$1"
		
		#sed -i "/\bexample\b/d" myfile
		
		#Get all the commands for the task, they are separated with ":".
		task_commands=$(echo $task| cut -d',' -f 4)
		#Get numner of commands
		#number of ':' is the occurrences
		number_of_occurrences=$(grep -o ":" <<< $task_commands | wc -l)		
		let number_of_occurrences=number_of_occurrences+2
		echo $number_of_occurrences
		
		#Prepare an array of all task commands.
		ARRAY=()
		COUNTER=1
        while [ $COUNTER -lt $number_of_occurrences ]; do
			echo The counter is $COUNTER
			task_command=$(echo $task_commands| cut -d':' -f $COUNTER)
			echo $task_command
			task_command="$task_command,"
			ARRAY[$COUNTER-1]=$task_command
            let COUNTER=COUNTER+1 
        done
		
		#let COUNTER=COUNTER-1
		echo ${ARRAY[*]}
		
		task_user=$(echo $task| cut -d',' -f 1)
		task_id=$(echo $task| cut -d',' -f 3)
		task_email=$(echo $task| cut -d',' -f 5)
		task_name=$(echo $task| cut -d',' -f 2)
		#echo $task_commands
		echo $task_user
		echo $task_id
		echo $task_email
		echo $task_name
		./bashrun $task_user $task_name $task_id $task_email $COUNTER "${ARRAY[*]}"
		
		#break;
	else
		echo "not new"		
	fi
done < "$1"


